export const contact = {
  name: "Yifeng Evan Shi",
  immigration: "U.S. Permanent Resident",
  role: "Software Engineer",
  location: "Los Angeles, Remote",
  education: {
    institution: "University of California, Los Angeles",
    degree: "Computer Science, B.S.",
    school: "School of Engineering"
  }
};

export const honors = [
  "Workday LEAD",
  "Workday Outstanding Contributor",
  "Tau Beta Pi Honor Society",
  "Upsilon Pi Epsilon Honor Society",
]

export const history = [
  {
    name: "Workday",
    roles: [
      {
        title: "Principal Software Engineer",
        org: "Extend",
        start: "2019",
        end: "Current",
        achievements: [
          "I define technical vision and drive innovation in developer experience for tools and services built in React + Typescript, Spring + Kotlin, and deployed on AWS",
          "Spearheaded launch of drag and drop RPA authoring web application by aligning transatlantic teams on technical designs of distributed microservices architecture",
          "Scaled consistent business behaviors for authentication and application logic across multiple feature teams by  publishing shareable software libraries on both JVM and JS platforms",
        ],
      },
      {
        title: "Senior Software Engineer",
        org: "App Creator",
        start: "2017",
        end: "2019",
        achievements: [
          "Led development of App Creator from design to launch; AC was featured at Rising 2018 keynote as a drag and drop web tool built with React for business administrators to connect APIs to extend Workday",
          "Empowered customers with intuitive UX by abstracting complex domain problems like data fetching, binding, context-sensitive expressions and declarative UI configurations",
          "Collaborated with many groups across Workday to implement infrastructure in service discovery, TLS, metrics, and logging",
        ],
      },
      {
        title: "Software Engineer",
        org: "UI Platform",
        start: "2014",
        end: "2016",
        achievements: [
          "Created concurrent, reactive API request engine with Scala for launch of public Workday Recruiting product on new external VPS platform",
          "Designed and implemented HTML + SVG org chart visualization by superimposing GWT components over our augmented d3.js tree algorithm and canvas",
          "One of two engineers who maintained Workday's fork of Chromium, Open Frame",
        ],
      },
      {
        title: "Software Engineer Intern",
        org: "UI Client",
        start: "2013",
        achievements: [
          "Delivered integral rich text editor component and a migration path from legacy data generated by Flash through a performant on-the-fly XML transformer algorithm between proprietary data formats and new HTML5 standard, including protections against XSS",
        ],
      },
    ],
  },
];

export const skills = [
  "React",
  "Redux",
  "Typescript",
  "node",
  "Spring",
  "Kotlin",
  "Java",
  "CSS",
  "SQL",
  "Scala",
  "Play!",
  "Gradle",
  "Docker",
  "kubernetes",
  "AWS",
  "REST",
  "OAuth",
  "JWT",
  "Terraform",
  "GraphQL",
  "Emotion",
  "Jest",
  "Jasmine",
  "Webpack",
  "Mockito",
  "Selenium",
  "Kafka",
  "Prometheus",
  "Jenkins",
  "Python",
  "C",
  "C++",
  "git",
  "bash",
  "OpenAPI",
  "d3",
  "GWT",
];
